### PR TITLE
Update CelsiusConverterGUI.java

### PR DESCRIPTION
**Pull request by Charlieee1**

### CODE REVIEW

**Comment by Charlieee1** [comment]
can you also follow me?

**Comment by bsaffin** [comment]
I am not sure what following you means. What do I have to do?

------ Original Message ------

**Comment by Charlieee1** [comment]
To follow me, you go to my profile: https://github.com/Charlieee1 and 
click the "Follow" button.

**Comment by Charlieee1** [comment]
Also, am I a collaborator?

**Comment by Charlieee1** [comment]
Can you make me Collaborator? To do so, go to settings, Manage Access, Add Collaborator.

**Comment by bsaffin** [comment]
There is no "manage access" option on my settings.

------ Original Message ------

**Comment by Charlieee1** [comment]
Do you have a column of buttons on the left side? It is there for me.

**Pull request closed without merging**
